=== Alex-NRCan/geoview/packages/geoview-about-panel/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "GeoView About Panel Schema",
  "type": "object",
  "version": "1.0",
  "comments": "Configuration for About Panel package.",
  "additionalProperties": false,
  "properties": {
    "isOpen": {
      "description": "Specifies whether the about panel is initially open or closed",
      "type": "boolean",
      "default": false
    },
    "aboutTitle": {
      "description": "The text that shows in the aria-label and at the very top of the About Panel",
      "type": "string"
    },
    "iconPath": {
      "description": "A path to an icon that will be used instead of the default icon for the about button",
      "type": "string"
    },
    "mdPath": {
      "description": "The relative path to a Markdown document to be embedded. Will override other configs.",
      "type": "string"
    },
    "mdContent": {
      "description": "A list of markdown items to add to the page",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "title": {
      "description": "The title for the about page",
      "type": "string"
    },
    "logoPath": {
      "description": "A relative path to an image logo to be placed under the title",
      "type": "string"
    },
    "description": {
      "description": "A description for the about panel",
      "type": "string"
    },
    "link": {
      "description": "A link to a website or page to direct users",
      "type": "string"
    },
    "version": {
      "type": "string",
      "enum": ["1.0"],
      "description": "The schema version used to validate the configuration file. The schema should enumerate the list of versions accepted by this version of the viewer.",
      "default": "1.0"
    }
  }
}

=== Alex-NRCan/geoview/packages/geoview-about-panel/default-config-about-panel.json
{
  "isOpen": true,
  "title": "Test About Page",
  "logoPath": "./logo.png",
  "description": "A long description about the page. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum porttitor enim sit amet odio euismod, vitae porta enim vestibulum. Fusce pulvinar, libero sed posuere elementum, turpis risus facilisis diam, in ornare enim quam sit amet dui. Vestibulum luctus nibh justo, a fermentum nisl efficitur eu. Fusce lobortis, orci et rhoncus semper, mauris neque pulvinar magna, vitae faucibus turpis sapien at metus. In imperdiet ligula tellus, eu vulputate nunc laoreet a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pellentesque imperdiet odio, sed facilisis elit fringilla vitae. Fusce lectus orci, luctus quis facilisis faucibus, dapibus ac justo. Phasellus a faucibus mauris. Ut et maximus quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin vel enim mattis, luctus arcu nec, lobortis metus. Suspendisse potenti. Etiam semper risus vel maximus finibus.\n\nIn viverra a ipsum sed vestibulum. Nunc posuere orci vel augue vestibulum, sed semper dolor tincidunt. Nam congue sagittis metus quis gravida. Morbi fringilla felis leo, eu eleifend nulla suscipit a. Sed bibendum orci non enim sollicitudin, eu luctus elit gravida. Nulla in ligula sed dolor tristique molestie ac fringilla nulla. Vestibulum sodales aliquam rhoncus. Aenean sit amet turpis accumsan, sagittis magna ut, facilisis nisi. Sed et elementum ipsum. Duis cursus ac elit in semper. Proin urna justo, placerat in malesuada vel, maximus eu purus.",
  "link": "https://natural-resources.canada.ca/science-data/science-research/research-centres/canada-centre-mapping-earth-observation"
}
